apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: memos-tryrocket-cloud-production
spec:
  secretName: memos-tryrocket-cloud-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: memos.tryrocket.cloud
  dnsNames:
    - 'memos.tryrocket.cloud'
