apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memos

resources:
  - ../../base
  - pvc.yaml

images:
  - name: neosmemo/memos:latest
    newTag: 0.23.1@sha256:f83b92889d4184710ee6ae8d9176c9f4c5d09a79e80c05c642b1b5adda29a385
