apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memos

resources:
  - ../../base
  - pvc.yaml

images:
  - name: neosmemo/memos:latest
    newTag: 0.24.2@sha256:12529e2117ad7a52d8aaba6e8d07218fcd1d8868b346b9585f583553b04f8533
