apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memos

resources:
  - ../../base
<<<<<<< HEAD
  - certificate.yaml
  - pvc.yaml
  - pv.yaml
=======
  - pvc.yaml
>>>>>>> 4840f39 (fixup! feat(app): add memos)

images:
  - name: neosmemo/memos:latest
    newTag: 0.22.4
