apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memos

resources:
  - ../../base
  - pvc.yaml

images:
  - name: neosmemo/memos:latest
    newTag: 0.23.0@sha256:d92b2c5dd6eb064cfb22c8a81a0a70b1c7a1d09068b30ddccd5e9d92cb6e300a
