apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memos

resources:
  - ../../base
  - pvc.yaml

images:
  - name: neosmemo/memos:latest
    newTag: 0.25.0@sha256:e278981311adb91712328cdd81d2f7bcf132f055b051338bbfaecf0538ba69fe
