apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memos

resources:
  - ../../base
  - pvc.yaml

images:
  - name: neosmemo/memos:latest
    newTag: 0.24.4@sha256:c6defc2dfb98fb97f78d86f94efb1464c959653cadf5123e1d4ad7452aefb973
