apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memos

resources:
  - ../../base
  - certificate.yaml
  - pvc.yaml
  - pv.yaml

images:
  - name: neosmemo/memos:latest
    newTag: 0.22.4
