services:
  mafl:
    image: hywax/mafl
    container_name: mafl
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - /home/dietpi/portainer/data/compose/3/docker/mafl/data:/app/data