services:
  mafl:
    image: hywax/mafl
    container_name: mafl
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      # - ./data/config.yml:/app/data/config.yml
      - ./home-ops/docker/mafl/data/config.yml:/app/data/config.yml

       