apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pvc.yaml

namespace: linkding

# https://github.com/sissbruecker/linkding/releases
images:
  - name: sissbruecker/linkding:latest
    newTag: 1.39.1-alpine@sha256:c91e4f0f69bf9a9228ea5dcdccd0df02c3461a29ace4c45362e240ceaf2daad6
