apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pvc.yaml

namespace: linkding

# https://github.com/sissbruecker/linkding/releases
images:
  - name: sissbruecker/linkding:latest
    newTag: 1.37.0-alpine@sha256:4d707f314d204757e1d9b368650e149aae6b7f1f3e21bc60c722d0e5105c2919
