apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pvc.yaml
  - pv.yaml

namespace: linkding

# https://github.com/sissbruecker/linkding/releases
images:
  - name: sissbruecker/linkding:latest
    newTag: 1.31.0-alpine
