apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: healthchecks-configuration-external-secret-test
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ionos-com-healthchecks-configuration-test
    creationPolicy: Owner
  data:
    - secretKey: HEALTHCHECKSIO_CHECK_UUID
      remoteRef:
        key: healthchecks.io/checks
        property: vaultwarden-export-backup-ionos-com-restic-hc-uuid
    - secretKey: HEALTHCHECKSIO_API_KEY
      remoteRef:
        key: healthchecks.io/checks
        property: API_KEY