apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: restic-repository-configuration-external-secret-test
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ionos-com-restic-repository-configuration-test
    creationPolicy: Owner
  data:
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: vaultwarden.tryrocket.cloud/backup/ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160/restic
        property: RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: vaultwarden.tryrocket.cloud/backup/ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160/restic
        property: RESTIC_PASSWORD
    - secretKey: PREFIX
      remoteRef:
        key: vaultwarden.tryrocket.cloud/backup/ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160/restic
        property: PREFIX