apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-credentials-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ionos-com-s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: ionos.com/objectstorage/users/1c670823-cb64-45f3-a543-aaedd096af3e
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: ionos.com/objectstorage/users/1c670823-cb64-45f3-a543-aaedd096af3e
        property: AWS_SECRET_ACCESS_KEY