services:
  caddy:
    image: ghcr.io/tryrocket-cloud/tryrocket-cloud:caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - /home/dietpi/portainer/data/compose/4/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}

networks:
  mafl_default:
    external: true