services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest@sha256:4a3d4afed443f026040cad84b48ef2eef6cc6eb5a80a3ecab66a03df469a46f8
    container_name: caddy
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - /home/dietpi/portainer/data/compose/7/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      # - /etc/ca.crt:/etc/ca.crt
      - ./data:/data
      - ./config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
#    networks:
#      - mafl_default
#      - semaphoreui_default
#      - portainer_default
#      - pocket-id_default
#      - pocket-id-lldap_default

#networks:
#  mafl_default:
#    external: true
#  semaphoreui_default:
#    external: true
#  portainer_default:
#    external: true
#  pocket-id_default:
#    external: true
#  pocket-id-lldap_default:
 #   external: true
