apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opengist
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  sources:
    # - repoURL: https://helm.opengist.io
    #   targetRevision: v0.1.0
    #   chart: opengist
    #   helm:
    #     valueFiles:
    #       - $values/k8s/opengist/values.yaml

    # - repoURL: https://github.com/tryrocket-cloud/home-ops.git
    #   targetRevision: main
    #   ref: values

    - repoURL: https://github.com/tryrocket-cloud/home-ops.git
      targetRevision: main
      path: 'k8s/opengist/overlays/production'

  destination:
    server: https://kubernetes.default.svc
    namespace: opengist

  info:
    - name: 'Helm Chart'
      value: 'https://helm.opengist.io'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
