services:
  pocketid:
    image: ghcr.io/pocket-id/pocket-id
    container_name: pocketid
    restart: unless-stopped
    environment:
      - PUBLIC_APP_URL=https://id.tryrocket.cloud
      - TRUST_PROXY=true
      - MAXMIND_LICENSE_KEY=
      - PUID=1000
      - PGID=1000
    volumes:
      - "./data:/app/backend/data"
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s