apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ionos.com-restic-repository-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ionos.com-restic-repository-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: vault.tryrocket.cloud/backup/ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160/restic