apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-token-secret
spec:
  refreshInterval: "168h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: vault-token-secret
    creationPolicy: Owner
  data:
    - secretKey: VAULT_TOKEN
      remoteRef:
        key: vault.tryrocket.cloud/users/cc57cdf5-30eb-4016-ac22-a60a3133e092
        property: token
---
