apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mafl

resources:
  - ../../base
  - certificate.yaml

configMapGenerator:
  - name: mafl-config
    files:
      - config.yml=config.yaml
