apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-export-backup
spec:
  suspend: false
  schedule: "2 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: truenas-tryrocket-cloud-objectstorage-backup
              image: ghcr.io/tryrocket-cloud/tryrocket-cloud:backup
              imagePullPolicy: Always
              env:
                - name: VAULT_EXPORT_JSON
                  value: /export/vault-export.json
              envFrom:
                - secretRef:
                    name: truenas-tryrocket-cloud-s3-bucket-configuration
                - secretRef:
                    name: truenas-tryrocket-cloud-s3-credentials
              command: ["/bin/sh", "-c"]
              args:
                - |
                  VAULT_EXPORT_WITH_DATE_JSON="${VAULT_EXPORT_JSON%.*}-$(date +'%Y-%m-%d_%H-%M-%S').${VAULT_EXPORT_JSON##*.}"

                  aws --endpoint-url $ENDPOINT s3 cp $VAULT_EXPORT_JSON s3://$BUCKET/vault/backup$VAULT_EXPORT_WITH_DATE_JSON # TODO: missing / in path
              volumeMounts:
                - name: vault-export-volume
                  mountPath: /export
                  readOnly: true