apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-credentials-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: truenas-tryrocket-cloud-s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: truenas.tryrocket.cloud/objectstorage/users/bdfb6446-30bf-4252-9ce5-91cc4605e3a4
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: truenas.tryrocket.cloud/objectstorage/users/bdfb6446-30bf-4252-9ce5-91cc4605e3a4
        property: AWS_SECRET_ACCESS_KEY
