apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lldap
  template:
    metadata:
      labels:
        app: lldap
    spec:
      containers:
        - name: lldap
          image: lldap/lldap:stable-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 17170
            - name: ldap
              containerPort: 3890
          env:
            - name: TZ
              value: Europe/Berlin
            - name: UID
              value: "1000"
            - name: GID
              value: "1000"
            - name: LLDAP_VERBOSE
              value: "true"
            - name: LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET
              value: "true"

          envFrom:
            - secretRef:
                name: ldap-config
            - secretRef:
                name: smtp-config
          volumeMounts:
            - name: lldap-volume
              mountPath: /etc/lldap/data
      volumes:
        - name: lldap-volume
          persistentVolumeClaim:
            claimName: lldap-pvc
