apiVersion: v1
kind: Service
metadata:
  name: lldap
spec:
  type: ClusterIP
  selector:
    app: lldap
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: ldap
      protocol: TCP
      port: 3890
      targetPort: ldap