apiVersion: apps/v1
kind: Deployment
metadata:
  name: papra
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: papra
  template:
    metadata:
      labels:
        app: papra
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: papra
          image: ghcr.io/papra-hq/papra:latest@sha256:1c28496700e35d646e84fd9f6441e32c11698b1971dce7bfae76125fd1d0ece6
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Berlin
            - name: CLIENT_BASE_URL
              value: https://docs.tryrocket.cloud
          ports:
            - name: http
              containerPort: 1221
              protocol: TCP
          volumeMounts:
            - name: papra-volume
              mountPath: /papra
      volumes:
        - name: papra-volume
          persistentVolumeClaim:
            claimName: papra-pvc
