apiVersion: apps/v1
kind: Deployment
metadata:
  name: papra
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: papra
  template:
    metadata:
      labels:
        app: papra
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: papra
          image: ghcr.io/papra-hq/papra:latest@sha256:a281cb44176dbe5323e0f7ea2d6fd34d58914a3a8525c36437a086d1d7c4fef8
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Berlin
            - name: CLIENT_BASE_URL
              value: https://docs.tryrocket.cloud
          ports:
            - name: http
              containerPort: 1221
              protocol: TCP
          volumeMounts:
            - name: papra-volume
              mountPath: /papra
      volumes:
        - name: papra-volume
          persistentVolumeClaim:
            claimName: papra-pvc
