apiVersion: apps/v1
kind: Deployment
metadata:
  name: papra
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: papra
  template:
    metadata:
      labels:
        app: papra
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: papra
          image: ghcr.io/papra-hq/papra:latest@sha256:6fdc2208f403882f4a3b8103a8aa7c2832e285f01205d54c24a9458c66607ba0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Berlin
            - name: CLIENT_BASE_URL
              value: https://docs.tryrocket.cloud
          ports:
            - name: http
              containerPort: 1221
              protocol: TCP
          volumeMounts:
            - name: papra-volume
              mountPath: /papra
      volumes:
        - name: papra-volume
          persistentVolumeClaim:
            claimName: papra-pvc
