apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memos
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tryrocket-cloud/home-ops.git
    path: 'k8s/memos/overlays/production'
    targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: memos

  info:
    - name: 'Helm Chart repository'
      value: 'https://github.com/usememos/helm'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
