# kubectl apply -f https://raw.githubusercontent.com/tryrocket-cloud/home-ops/refs/heads/main/k8s/application-set.yaml -n argocd
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-chart-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # - name: cert-manager
          #   chart: cert-manager
          #   repoURL: https://charts.jetstack.io
          #   targetRevision: v1.16.1
          #   namespace: cert-manager

          # - name: external-secrets
          #   chart: external-secrets
          #   repoURL: https://charts.external-secrets.io
          #   targetRevision: '0.10.5'
          #   namespace: external-secrets

          # - name: kubernetes-dashboard
          #   chart: kubernetes-dashboard
          #   repoURL: https://kubernetes.github.io/dashboard/
          #   targetRevision: '7.10.0'
          #   namespace: kubernetes-dashboard

          # - name: gitea
          #   chart: gitea
          #   repoURL: https://dl.gitea.com/charts/
          #   targetRevision: 'v10.6.0'
          #   namespace: gitea

  template:
    metadata:
      name: '{{name}}'
      labels:
        app.kubernetes.io/managed-by: argocd
    spec:
      project: default
      sources:
        - repoURL: '{{repoURL}}'
          chart: '{{chart}}'
          targetRevision: '{{targetRevision}}'
          helm:
            valueFiles:
              - $values/k8s/{{name}}/values.yaml

        - repoURL: https://github.com/tryrocket-cloud/home-ops.git
          targetRevision: main
          ref: values

        - repoURL: https://github.com/tryrocket-cloud/home-ops.git
          path: 'k8s/{{name}}'
          targetRevision: main

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
