apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pvc.yaml
  - ldap-external-secret.yaml
  - smtp-external-secret.yaml
#  - ingressRouteTCP.yaml

namespace: lldap

images:
  - name: lldap/lldap:latest
    newTag: stable@sha256:2a8454b668c1aba7157e832eab0e242e1e7eb5fb7591d7e7774ba05286511ca8
