apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-config-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: smtp-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ldap.tryrocket.cloud/smtp