apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-vaultwarden-export
spec:
  suspend: true
  schedule: "0 22 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: test-restic-backup
              image: ghcr.io/tryrocket-cloud/home-ops:toolkit
              imagePullPolicy: Always
              env:
                - name: RESTIC_CACHE_DIR
                  value: /root/.cache/restic/vaultwarden
                - name: KOPIA_CACHE_DIRECTORY
                  value: /root/.cache/kopia/vaultwarden
                - name: HOSTNAME
                  value: tryrocket.cloud
              envFrom:
                - secretRef:
                    name: all-in-one
              args: ["backup-vaultwarden"]
              volumeMounts:
                - name: support-volume
                  mountPath: /root/.cache
                  readOnly: false
          volumes:
            - name: support-volume
              persistentVolumeClaim:
                claimName: vaultwarden-support-pvc
