apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ionos-com-objectstorage-bucket-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ionos-com-objectstorage-bucket-secret
    creationPolicy: Owner
  data:
    - secretKey: BUCKET
      remoteRef:
        key: ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160
        property: name
    - secretKey: ENDPOINT
      remoteRef:
        key: ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160
        property: endpoint
    - secretKey: REGION
      remoteRef:
        key: ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160
        property: region
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ionos-com-objectstorage-user-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ionos-com-objectstorage-user-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: ionos.com/users/1c670823-cb64-45f3-a543-aaedd096af3e
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: ionos.com/users/1c670823-cb64-45f3-a543-aaedd096af3e
        property: AWS_SECRET_ACCESS_KEY