apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mafl
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tryrocket-cloud/home-ops.git
    targetRevision: main
    path: 'k8s/mafl/overlays/production'

  destination:
    server: https://kubernetes.default.svc
    namespace: mafl

  info:
    - name: 'Example:'
      value: 'https://example.com'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
