services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - /home/dietpi/upsnap/data:/app/pb_data
    user: 1000:1000
    environment:
      - TZ=Europe/Berlin
