---
services:
  caddy:
    image: ghcr.io/tryrocket-cloud/tryrocket-cloud:caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - './caddy/config:/config'
      - './caddy/data:/data'
      - './caddy/Caddyfile:/etc/caddy/Caddyfile'
