services:
  adguardhome:
    image: adguard/adguardhome:latest@sha256:c64a0b37f7b9f7e065089f34686c1232a4dd5401a199a1b20b074d90b955eebd
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "3001:80"
      - "3000:3000"
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
