services:
  caddy:
    container_name: caddy
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy/config:/config
      - ./caddy/data:/data
#      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
