services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./upsnap/data:/app/pb_data
    environment:
      - TZ=Europe/Berlin
      - UPSNAP_INTERVAL=@every 5m
      - UPSNAP_SCAN_RANGE=192.168.178.0/24
      - UPSNAP_WEBSITE_TITLE=Rocket Cloud
