apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-vaultwarden-export
  annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-secret-restic_env_list.yaml: "kv/data/restic_env_list"
  vault.hashicorp.com/agent-inject-template-restic_env_list.yaml: |
    {{ with secret "kv/data/restic_env_list" }}
    {{ .Data.data | to_nice_yaml }}
    {{ end }}
spec:
  suspend: false
  schedule: "0 22 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: test-restic-backup
              image: ghcr.io/tryrocket-cloud/home-ops:toolkit
              imagePullPolicy: Always
              env:
                - name: RESTIC_CACHE_DIR
                  value: /cache/ionos.com/vaultwarden/restic
              envFrom:
                - secretRef:
                    name: all-in-one
              args: ["backup-vaultwarden"]
          #     volumeMounts:
          #       - name: support-volume
          #         mountPath: /cache/ionos.com/vaultwarden/restic
          #         readOnly: true
          # volumes:
          #   - name: support-volume
          #     persistentVolumeClaim:
          #       claimName: support-volume-claim
