apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-longhorn-credential-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: longhorn-credential-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: truenas.tryrocket.cloud/objectstorage/users/6d02eb6c-a179-4288-9016-8de00601307b
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: truenas.tryrocket.cloud/objectstorage/users/6d02eb6c-a179-4288-9016-8de00601307b
        property: AWS_SECRET_ACCESS_KEY
 