apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.16.1
      chart: cert-manager
      helm:
        valueFiles:
          - $values/k8s/cert-manager/values.yaml

    - repoURL: https://github.com/tryrocket-cloud/home-ops.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/tryrocket-cloud/home-ops.git
      path: 'k8s/cert-manager'
      targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  info:
    - name: 'Example:'
      value: 'https://example.com'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
