apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tryrocket-cloud-production-cert
  namespace: default
spec:
  secretName: tryrocket-cloud-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.tryrocket.cloud"
  dnsNames:
    - "*.tryrocket.cloud"
    - "tryrocket.cloud"
