apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: all-in-one-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: all-in-one
    creationPolicy: Owner
  data:
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: vault.tryrocket.cloud/backup/ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160/restic
        property: RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: vault.tryrocket.cloud/backup/ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160/restic
        property: RESTIC_PASSWORD
    - secretKey: HEALTHCHECKSIO_CHECK_UUID
      remoteRef:
        key: healthchecks.io/checks
        property: vault-export-backup-ionos-com-restic-hc-uuid
    - secretKey: HEALTHCHECKSIO_API_KEY
      remoteRef:
        key: healthchecks.io/checks
        property: API_KEY
    - secretKey: VAULT_TOKEN
      remoteRef:
        key: vault.tryrocket.cloud/users/cc57cdf5-30eb-4016-ac22-a60a3133e092
        property: token
  #     remoteRef:
  #       key: ionos.com/objectstorage/users/fe4a46ce-1234-4b07-b143-efa888a87258
  #       property: AWS_ACCESS_KEY_ID
  #   - secretKey: AWS_SECRET_ACCESS_KEY
  #     remoteRef:
  #       key: ionos.com/objectstorage/users/fe4a46ce-1234-4b07-b143-efa888a87258
  #       property: AWS_SECRET_ACCESS_KEY
  #   - secretKey: BUCKET
  #     remoteRef:
  #       key: ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160
  #       property: name
  #   - secretKey: ENDPOINT
  #     remoteRef:
  #       key: ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160
  #       property: endpoint
  #   - secretKey: REGION
  #     remoteRef:
  #       key: ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160
  #       property: region
  # dataFrom:
  #   - extract:
  #       key: vault.tryrocket.cloud/backup/ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160/kopia