apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-vault-export
spec:
  suspend: false
  schedule: "0 22 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: backup-vault-export
              image: ghcr.io/tryrocket-cloud/home-ops:toolkit@sha256:74cc559f0926651ac8f124b6fde9de0994b104395501b7f9c745d7762bb84be0
              imagePullPolicy: Always
              env:
                - name: RESTIC_CACHE_DIR
                  value: /root/.cache/restic/vault
                - name: KOPIA_CACHE_DIRECTORY
                  value: /root/.cache/kopia/vault
                - name: HOSTNAME
                  value: tryrocket.cloud
              envFrom:
                - secretRef:
                    name: all-in-one
              args: ["backup-vault"]
              volumeMounts:
                - name: support-volume
                  mountPath: /root/.cache
                  readOnly: false
          volumes:
            - name: support-volume
              persistentVolumeClaim:
                claimName: vault-support-pvc
