help:
    @just --list

build:
    @docker buildx build --platform linux/amd64 -t tryrocket.cloud/backup:latest . --load

backup env_file target:
	@docker run --rm \
	  --platform linux/amd64 \
	  -v $(pwd)/.cache/restic:/root/.cache/restic \
	  --env-file {{env_file}} \
	  tryrocket.cloud/backup:latest {{target}}

backup-vaultwarden:
	@just backup .env.vaultwarden backup-vaultwarden

backup-vault:
	@just backup .env.vault backup-vault