apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: healthchecks-configuration-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: truenas-tryrocket-cloud-healthchecks-configuration
    creationPolicy: Owner
  data:
    - secretKey: VAULTWARDEN_EXPORT_BACKUP_TRUENAS_TRYROCKET_CLOUD_HC_UUID
      remoteRef:
        key: healthchecks.io/checks
        property: vaultwarden-export-backup-truenas-tryrocket-cloud-hc-uuid