apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: restic-repository-configuration-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ionos-com-restic-repository-configuration
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: vault.tryrocket.cloud/backup/ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160/restic