- name: Get kopia version output
  command: kopia --version
  register: kopia_version_output

- name: Extract version using split
  set_fact:
    kopia_version: "{{ kopia_version_output.stdout.split()[0] }}"

- name: Kopia repository connect
  shell: kopia repository connect s3 \
    --bucket={{ bucket }} \
    --prefix={{ prefix }} \
    --region={{ region }} \
    --endpoint={{ endpoint }}
  environment: "{{ kopia_env }}"
  register: kopia_connect_result

- name: Construct Kopia extra tags string
  set_fact:
    extra_tags_string: >-
      {%- set tags = [] -%}
      {%- for item in extra_backup_tags | dict2items -%}
      {%- set _ = tags.append(item.key ~ ':' ~ item.value) -%}
      {%- endfor -%}
      {{ tags | join(' ') }}

- name: Perform Kopia backup
  shell: kopia snapshot create "{{ backup_paths | join(' ') }}" \
    --description="Daily export" \
    --tags="kopia_version:{{ kopia_version }} hostname:{{ lookup('ansible.builtin.env', 'HOSTNAME') | default(ansible_hostname, true) }} {{ extra_tags_string }}"
  environment: "{{ kopia_env }}"
  register: kopia_backup_result

- name: Perform Kopia consistency check
  shell: kopia snapshot verify --verify-files-percent 33
  environment: "{{ kopia_env }}"
  register: kopia_verify_result
