services:
  semaphore:
    image: semaphoreui/semaphore:v2.13.14@sha256:f80861af83c7381963b3a2190379f59c431be702aaa740f0c4c7f166b48d6de0
    container_name: semaphore
    environment:
      TZ: Europe/Berlin
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN}
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_SLACK_ALERT: "True"
      SEMAPHORE_SLACK_URL: ${SEMAPHORE_SLACK_URL}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
    volumes:
      - ./semaphore/data:/var/lib/semaphore
      - ./semaphore/config:/etc/semaphore
