services:
  semaphore:
    image: semaphoreui/semaphore:v2.19.14@sha256:98ad9bc7a2a03001a725c90d37c9e500b951da3175d51cd36337e9c1cf7ea9aa
    container_name: semaphore
    environment:
      TZ: Europe/Berlin
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN}
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_SLACK_ALERT: "True"
      SEMAPHORE_SLACK_URL: ${SEMAPHORE_SLACK_URL}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
    volumes:
      - ./semaphore/data:/var/lib/semaphore
      - ./semaphore/config:/etc/semaphore
