apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: admin-token
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: admin-token
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: vaultwarden.tryrocket.cloud/users/admin
        property: admin-token
