apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vaultwarden-0
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-retain
