apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: smtp
    creationPolicy: Owner
  data:
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: vaultwarden.tryrocket.cloud/smtp
        property: SMTP_USERNAME
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: vaultwarden.tryrocket.cloud/smtp
        property: SMTP_PASSWORD