apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: healthchecks-configuration-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ionos-com-healthchecks-configuration
    creationPolicy: Owner
  data:
    - secretKey: KOPIA_HC_UUID
      remoteRef:
        key: healthchecks.io/checks
        property: vaultwarden-export-backup-ionos-com-kopia-hc-uuid
    - secretKey: RESTIC_HC_UUID
      remoteRef:
        key: healthchecks.io/checks
        property: vaultwarden-export-backup-ionos-com-restic-hc-uuid