apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-bucket-configuration-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ionos-com-s3-bucket-configuration
    creationPolicy: Owner
  data:
    - secretKey: BUCKET
      remoteRef:
        key: ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160
        property: name
    - secretKey: ENDPOINT
      remoteRef:
        key: ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160
        property: endpoint
    - secretKey: REGION
      remoteRef:
        key: ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160
        property: region
