apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opengist

resources:
  - ../../base
  - pvc.yaml
  # - pv.yaml

# https://github.com/thomiceli/opengist/releases
images:
  - name: ghcr.io/thomiceli/opengist:latest
    newTag: 1.8.4@sha256:c385001a3efdebe03f075a38145890d234412bd5a879ff04f5f39a033bdd8eac
