apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opengist

resources:
  - ../../base
  - pvc.yaml
  - oidc-external-secret.yaml

# https://github.com/thomiceli/opengist/releases
images:
  - name: ghcr.io/thomiceli/opengist:latest
    newTag: 1.9.1@sha256:75fc200bde38459be4e3aed5e40ef2e3076fddcca5eb6bd08ebd0c7d7a939d85
