apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opengist

resources:
  - ../../base
  - certificate.yaml

# https://github.com/thomiceli/opengist/releases
images:
  - name: ghcr.io/thomiceli/opengist:latest
    newTag: 1.7.3
