apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: oidc
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: opengist.tryrocket.cloud/oidc