apiVersion: v1
kind: PersistentVolume
metadata:
  name: opengist-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-retain
  csi:
    driver: driver.longhorn.io
    volumeHandle: pvc-46a7cdf3-f41b-4172-9804-9d05e8022c56
