apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: answer
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/apache/incubator-answer.git
      targetRevision: main
      path: charts
      helm:
        valueFiles:
          - $values/k8s/answer/values.yaml

    - repoURL: https://github.com/tryrocket-cloud/home-ops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: answer

  info:
    - name: Homepage
      value: https://answer.apache.org/
    - name: GitHub
      value: https://github.com/apache/incubator-answer/tree/main
    - name: Helm Chart
      value: https://github.com/apache/incubator-answer/charts
    - name: Helm Chart values
      value: https://github.com/apache/incubator-answer/blob/main/charts/values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
