- name: Backup Vaultwarden export with restic 
  hosts: localhost
  gather_facts: true

  vars:
    healthchecks_uuid: "{{ lookup('ansible.builtin.env', 'HEALTHCHECKSIO_CHECK_UUID') }}"
    healthchecks_api_key: "{{ lookup('ansible.builtin.env', 'HEALTHCHECKSIO_API_KEY') }}"
    
    restic_env:
      AWS_ACCESS_KEY_ID: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
      AWS_SECRET_ACCESS_KEY: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
      RESTIC_REPOSITORY: "{{ lookup('ansible.builtin.env', 'RESTIC_REPOSITORY') }}"
      RESTIC_PASSWORD: "{{ lookup('ansible.builtin.env', 'RESTIC_PASSWORD') }}"

  tasks:
    - block:
        - include_tasks: common-restic.yaml

        - name: Signal success to healthchecks.io
          community.healthchecksio.ping:
            state: present
            uuid: "{{ healthchecks_uuid }}"
            api_key: "{{ healthchecks_api_key }}"
            signal: "success"

      rescue:
        - name: Signal failure to healthchecks.io
          community.healthchecksio.ping:
            state: present
            uuid: "{{ healthchecks_uuid }}"
            api_key: "{{ healthchecks_api_key }}"
            signal: "fail"
