- name: Backup Vaultwarden export with kopia 
  hosts: localhost
  gather_facts: true

  vars:
    healthchecks_uuid: "{{ lookup('ansible.builtin.env', 'HEALTHCHECKSIO_CHECK_UUID') }}"
    healthchecks_api_key: "{{ lookup('ansible.builtin.env', 'HEALTHCHECKSIO_API_KEY') }}"
      
    prefix: "{{ lookup('ansible.builtin.env', 'PREFIX') }}"
    endpoint: "{{ lookup('ansible.builtin.env', 'ENDPOINT') }}"
    region: "{{ lookup('ansible.builtin.env', 'REGION') }}"
    bucket: "{{ lookup('ansible.builtin.env', 'BUCKET') }}"

    kopia_env:
      AWS_ACCESS_KEY_ID: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
      AWS_SECRET_ACCESS_KEY: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
      KOPIA_PASSWORD: "{{ lookup('ansible.builtin.env', 'KOPIA_PASSWORD') }}"
      KOPIA_CHECK_FOR_UPDATES: false

  tasks:
    - block:
        - include_tasks: common-kopia.yaml

        - name: Signal success to healthchecks.io
          community.healthchecksio.ping:
            state: present
            uuid: "{{ healthchecks_uuid }}"
            api_key: "{{ healthchecks_api_key }}"
            signal: "success"

      rescue:
        - name: Signal failure to healthchecks.io
          community.healthchecksio.ping:
            state: present
            uuid: "{{ healthchecks_uuid }}"
            api_key: "{{ healthchecks_api_key }}"
            signal: "fail"
