apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - ingress.yaml
  - https-redirect-middleware.yaml
  - basic-auth-middleware.yaml

namespace: kube-system
