apiVersion: apps/v1
kind: Deployment
metadata:
  name: opengist
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: opengist
  template:
    metadata:
      labels:
        app: opengist
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: opengist
          image: ghcr.io/thomiceli/opengist:latest@sha256:b3ae8c4614fcfc3099ed08317f0113444f314d3d390e89161cff9b673729d191
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Berlin
            - name: OG_LOG_LEVEL
              value: info
            - name: OG_EXTERNAL_URL
              value: https://opengist.tryrocket.cloud
            - name: OG_SSH_GIT_ENABLED
              value: "false"
          envFrom:
            - secretRef:
                name: oidc
          ports:
            - containerPort: 6157
            - containerPort: 2222
          volumeMounts:
            - name: opengist-volume
              mountPath: /opengist
      volumes:
        - name: opengist-volume
          persistentVolumeClaim:
            claimName: opengist-pvc
