ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kestra.tryrocket.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    - hosts:
      - kestra.tryrocket.cloud
      secretName: kestra-tryrocket-cloud-production-tls
