apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: all-in-one-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: all-in-one
    creationPolicy: Owner
  data:
    - secretKey: AGE_RECIPIENT
      remoteRef:
        key: tryrocket.cloud
        property: age.recipient
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: ionos.com/objectstorage/users/0e96e074-79a3-40bd-a828-0d044a7155a4
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: ionos.com/objectstorage/users/0e96e074-79a3-40bd-a828-0d044a7155a4
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: BUCKET
      remoteRef:
        key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
        property: name
    - secretKey: AWS_ENDPOINT_URL
      remoteRef:
        key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
        property: endpoint
    - secretKey: AWS_REGION
      remoteRef:
        key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
        property: region
    - secretKey: restic-policy.json
      remoteRef:
        key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
        property: restic-policy
    - secretKey: deny-all-policy.json
      remoteRef:
        key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
        property: deny-all-policy
    - secretKey: public-access-block-restic.json
      remoteRef:
        key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
        property: public-access-block-restic
    - secretKey: public-access-block-deny-all.json
      remoteRef:
        key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
        property: public-access-block-deny-all
    # - secretKey: RESTIC_REPOSITORY
    #   remoteRef:
    #     key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
    #     property: RESTIC_REPOSITORY
    # - secretKey: RESTIC_PASSWORD
    #   remoteRef:
    #     key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
    #     property: RESTIC_PASSWORD


    - secretKey: HEALTHCHECKSIO_CHECK_UUID
      remoteRef:
        key: healthchecks.io/checks
        property: vaultwarden-export-backup-ionos-com-restic-hc-uuid
    - secretKey: HEALTHCHECKSIO_API_KEY
      remoteRef:
        key: healthchecks.io/checks
        property: API_KEY
    - secretKey: VAULTWARDEN_USERNAME
      remoteRef:
        key: vaultwarden.tryrocket.cloud/users/33843b46-db47-43f3-a28b-adc0ec3e8bc9
        property: username
    - secretKey: VAULTWARDEN_PASSWORD
      remoteRef:
        key: vaultwarden.tryrocket.cloud/users/33843b46-db47-43f3-a28b-adc0ec3e8bc9
        property: password
    # - secretKey: AWS_ACCESS_KEY_ID
    #   remoteRef:
    #     key: ionos.com/objectstorage/users/1c670823-cb64-45f3-a543-aaedd096af3e
    #     property: AWS_ACCESS_KEY_ID
    # - secretKey: AWS_SECRET_ACCESS_KEY
    #   remoteRef:
    #     key: ionos.com/objectstorage/users/1c670823-cb64-45f3-a543-aaedd096af3e
    #     property: AWS_SECRET_ACCESS_KEY
    # - secretKey: BUCKET
    #   remoteRef:
    #     key: ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160
    #     property: name
    # - secretKey: AWS_ENDPOINT_URL
    #   remoteRef:
    #     key: ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160
    #     property: endpoint
    # - secretKey: AWS_REGION
    #   remoteRef:
    #     key: ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160
    #     property: region
  dataFrom:
    - extract:
        key: vaultwarden.tryrocket.cloud/backup/ionos.com/objectstorage/buckets/0d4b2020-eb43-4a33-bdb4-4c803d98f160/kopia