version: 2

backends:
  s3-main:
    type: s3
    path: '{{ env "AWS_ENDPOINT_URL" }}/{{ env "BUCKET" }}'
    env:
      AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY

locations:
  vaultwarden:
    from:
      - "/export"
    to:
      - s3-main
    forget:
      keep_last: 180
      prune: true
