apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-vaultwarden-export-2
spec:
  suspend: false
  schedule: "0 22 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never

          initContainers:
            - name: get-vaultwarden-version
              image: alpine/curl
              env:
                - name: VAULTWARDEN_HOST
                  value: vaultwarden.tryrocket.cloud
              command:
                - sh
                - -c
                - |
                  set -euo pipefail

                  apk add --no-cache curl jq bind-tools

                  ping -c1 -W2 "${VAULTWARDEN_HOST}" >/dev/null

                  version=$(curl -sSf -m10 https://"${VAULTWARDEN_HOST}"/api/config | jq -r '.version // empty')
                  if [ -z "$version" ]; then
                    echo "ERROR: no .version in API response" >&2
                    exit 1
                  fi

                  echo "VAULTWARDEN_VERSION=${version}" > /export/vaultwarden.env
                  echo "Fetched Vaultwarden version: $version"

          containers:
            - name: test
              image: alpine:3.16
              env:
                - name: VAULTWARDEN_HOST
                  value: https://vaultwarden.tryrocket.cloud
              command:
                - sh
                - -c
                - |
                  echo test
          volumes:
            - name: support-volume
              persistentVolumeClaim:
                claimName: vaultwarden-support-pvc
