apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-vaultwarden-export-2
spec:
  suspend: false
  schedule: "0 22 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never

          volumes:
            - name: vaultwarden-export-volume
              emptyDir: {}
            - name: support-volume
              persistentVolumeClaim:
                claimName: vaultwarden-support-pvc

          initContainers:
            - name: get-vaultwarden-version
              image: alpine/curl
              env:
                - name: VAULTWARDEN_HOST
                  value: vaultwarden.tryrocket.cloud
              command:
                - sh
                - -c
                - |
                  set -euo pipefail

                  apk add --no-cache curl jq

                  curl -sSf -m10 https://"${VAULTWARDEN_HOST}"/api/config \
                    | jq -r '.version // error("no version in API response")' \
                    > /export/vaultwarden.env
              volumeMounts:
                - name: vaultwarden-export-volume
                  mountPath: /export

            - name: export-vaultwarden-33843b46-db47-43f3-a28b-adc0ec3e8bc9
              image: debian:bookworm-slim
              imagePullPolicy: Always
              env:
                - name: VAULTWARDEN_HOST
                  value: vaultwarden.tryrocket.cloud
                - name: VAULTWARDEN_EXPORT_JSON
                  value: /export/vaultwarden-export-33843b46-db47-43f3-a28b-adc0ec3e8bc9.json
                - name: EXPORT_PASSWORD      # TODO: change to your real passphrase
                  value: test
                - name: BW_CLI_VERSION
                  value: 2025.4.0
              envFrom:
                - secretRef:
                    name: all-in-one
              command: ["/bin/sh","-c"]
              args:
                - |
                  set -euxo

                  # install dependencies
                  apt-get update
                  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
                    curl unzip ca-certificates \
                  && rm -rf /var/lib/apt/lists/*

                  # download & install bw
                  DOWNLOAD_URL="https://github.com/bitwarden/cli/releases/download/v${BW_CLI_VERSION}/bw-linux-64bit.zip"
                  curl -fsSL "$DOWNLOAD_URL" -o /tmp/bw.zip
                  unzip -qo /tmp/bw.zip -d /usr/local/bin
                  chmod +x /usr/local/bin/bw
                  rm /tmp/bw.zip

                  # verify install
                  which bw
                  bw --version

                  # perform the encrypted export
                  bw config server "https://${VAULTWARDEN_HOST}"
                  export BW_SESSION=$(bw login --raw "$username" "$password")
                  bw sync
                  bw export \
                    --format encrypted_json \
                    --password "$EXPORT_PASSWORD" \
                    --output "$VAULTWARDEN_EXPORT_JSON"
                  bw logout

                  # ensure we got a file
                  [ -s "$VAULTWARDEN_EXPORT_JSON" ] \
                    || { echo "ERROR: export failed or produced empty file" >&2; exit 1; }

                  cat "$VAULTWARDEN_EXPORT_JSON"
              volumeMounts:
                - name: vaultwarden-export-volume
                  mountPath: /export

          containers:
            - name: test
              image: alpine:3.16
              env:
                - name: VAULTWARDEN_HOST
                  value: https://vaultwarden.tryrocket.cloud
              command:
                - sh
                - -c
                - |
                  echo test

