apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-vaultwarden-export-2
spec:
  suspend: false
  schedule: "0 22 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never

          volumes:
            - name: vaultwarden-export-volume
              emptyDir: {}
            - name: support-volume
              persistentVolumeClaim:
                claimName: vaultwarden-support-pvc
            - name: restic-policy
              secret:
                secretName: all-in-one
                items:
                  - key: restic-policy.json
                    path: restic-policy.json
            - name: deny-all-policy
              secret:
                secretName: all-in-one
                items:
                  - key: deny-all-policy.json
                    path: deny-all-policy.json
            - name: public-access-block-restic
              secret:
                secretName: all-in-one
                items:
                  - key: public-access-block-restic.json
                    path: public-access-block-restic.json
            - name: public-access-block-deny-all
              secret:
                secretName: all-in-one
                items:
                  - key: public-access-block-deny-all.json
                    path: public-access-block-deny-all.json

          initContainers:
            - name: healthcheck-start
              image: curlimages/curl
              envFrom:
                - secretRef:
                    name: healthchecksio
              command: ["/bin/sh","-c"]
              args:
                - |
                  set -eu pipefail
                  curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID/start

            - name: get-vaultwarden-version
              image: alpine/curl
              env:
                - name: VAULTWARDEN_HOST
                  value: vaultwarden.tryrocket.cloud
              command:
                - sh
                - -c
                - |
                  set -euo pipefail

                  apk add --no-cache curl jq

                  VW_VERSION=$(
                    curl -sSf -m10 "https://${VAULTWARDEN_HOST}/api/config" \
                      | jq -r '.version // error("no version in API response")'
                  )

                  echo "export VAULTWARDEN_VERSION=${VW_VERSION}" >> /export/vaultwarden.env
              volumeMounts:
                - name: vaultwarden-export-volume
                  mountPath: /export

            - name: export-2967ac9f-f0e5-4881-8be5-9d08371a167a
              image: debian:bookworm-slim
              env:
                - name: VAULTWARDEN_HOST
                  value: vaultwarden.tryrocket.cloud
                - name: VAULTWARDEN_USER_ID
                  value: 2967ac9f-f0e5-4881-8be5-9d08371a167a
                - name: VAULTWARDEN_EXPORT_JSON
                  value: 
                - name: BW_CLI_VERSION
                  value: 2025.4.0
              envFrom:
                - secretRef:
                    name: all-in-one
              command: ["/bin/sh","-c"]
              args:
                - |
                  set -euo

                  apt-get update
                  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
                    curl unzip ca-certificates \
                  && rm -rf /var/lib/apt/lists/*

                  curl -sSL --fail https://github.com/bitwarden/clients/releases/latest/download/bw-linux-${BW_CLI_VERSION}.zip -o /tmp/bw.zip
                  unzip -q /tmp/bw.zip -d /usr/local/bin && rm /tmp/bw.zip
                  chmod +x /usr/local/bin/bw
                  
                  echo "export BW_CLI_VERSION=$(bw --version)" >> /export/vaultwarden.env

                  bw config server https://${VAULTWARDEN_HOST}
                  export BW_SESSION=$(bw login --raw "${VAULTWARDEN_USERNAME}" "${VAULTWARDEN_PASSWORD}")
                  bw sync
                  bw export \
                    --format encrypted_json \
                    --password "${VAULTWARDEN_PASSWORD}" \
                    --output /export/vaultwarden-export-"${VAULTWARDEN_USER_ID}"-encrypted_json.json
                  bw export \
                    --format json \
                    --output /export/vaultwarden-export-"${VAULTWARDEN_USER_ID}"-plain.json
                  bw logout

                  [ -s "/export/vaultwarden-export-${VAULTWARDEN_USER_ID}-encrypted_json.json" ] || { echo "ERROR: export failed or produced empty file" >&2; exit 1; }
                  [ -s "/export/vaultwarden-export-${VAULTWARDEN_USER_ID}-plain.json" ] || { echo "ERROR: export failed or produced empty file" >&2; exit 1; }
              volumeMounts:
                - name: vaultwarden-export-volume
                  mountPath: /export

            - name: encrypt-with-age
              image: alpine:3.18
              env:
                - name: VAULTWARDEN_USER_ID
                  value: 2967ac9f-f0e5-4881-8be5-9d08371a167a
                - name: AGE_VERSION
                  value: 1.2.1
              envFrom:
                - secretRef:
                    name: all-in-one

              command: ["/bin/sh","-c"]
              args:
                - |
                  set -euo pipefail

                  apk add --no-cache curl tar gzip ca-certificates

                  curl -fsSL "https://github.com/FiloSottile/age/releases/latest/download/age-v${AGE_VERSION}-linux-amd64.tar.gz" \
                  | tar xz -C /usr/local/bin --strip-components=1
                  chmod +x /usr/local/bin/age /usr/local/bin/age-keygen

                  echo "export AGE_VERSION=$(age --version)" >> /export/vaultwarden.env

                  PLAIN="/export/vaultwarden-export-${VAULTWARDEN_USER_ID}-plain.json"
                  CIPHER="/export/vaultwarden-export-${VAULTWARDEN_USER_ID}.age"

                  [ -s "${PLAIN}" ] || { echo "ERROR: missing plaintext export" >&2; exit 1; }

                  age --recipient "${AGE_RECIPIENT}" --output "${CIPHER}" "${PLAIN}"

                  [ -s "${CIPHER}" ] || { echo "ERROR: age encryption failed" >&2; exit 1; }
                  head -c21 "${CIPHER}" | grep -q '^age-encryption\.org/v1'

                  rm "${PLAIN}"
              volumeMounts:
                - name: vaultwarden-export-volume
                  mountPath: /export

            - name: configure-s3-access-allowance
              image: public.ecr.aws/aws-cli/aws-cli:latest
              command: ["/bin/sh","-c"]
              args:
                - |
                  set -eu

                  aws s3api put-bucket-policy \
                    --bucket "${BUCKET}" \
                    --endpoint-url "${AWS_ENDPOINT_URL}" \
                    --policy file:///restic-policy.json

                  aws s3api put-public-access-block \
                    --bucket "${BUCKET}" \
                    --endpoint-url "${AWS_ENDPOINT_URL}" \
                    --public-access-block-configuration file:///public-access-block-restic.json

              envFrom:
                - secretRef:
                    name: all-in-one
              volumeMounts:
                - name: restic-policy
                  mountPath: /restic-policy.json
                  subPath: restic-policy.json
                  readOnly: true
                - name: public-access-block-restic
                  mountPath: /public-access-block-restic.json
                  subPath: public-access-block-restic.json
                  readOnly: true

            - name: restic
              image: restic/restic:0.18.0
              envFrom:
                - secretRef:
                    name: restic
              env:
                - name: RESTIC_CACHE_DIR
                  value: /cache/ionos.com/vaultwarden/restic
                - name: HOSTNAME
                  value: tryrocket.cloud
              command: ["/bin/sh","-c"]
              args:
                - |
                  set -eu

                  source /export/vaultwarden.env
                  export RESTIC_VERSION=$(restic version | awk 'NR==1{print $2}')

                  restic --verbose=2 backup \
                    --host $HOSTNAME \
                    --tag restic_version:$RESTIC_VERSION \
                    --tag bw_cli_version:$BW_CLI_VERSION \
                    --tag vaultwarden_version:$VAULTWARDEN_VERSION \
                    --tag age_version:$AGE_VERSION \
                    --tag environment:production \
                    /export
                  restic check --read-data
                  restic forget --keep-last 180 --prune

              volumeMounts:
                - name: support-volume
                  mountPath: /cache
                  readOnly: false
                - name: vaultwarden-export-volume
                  mountPath: /export

            - name: healthcheck-ping
              image: curlimages/curl
              envFrom:
                - secretRef:
                    name: healthchecksio
              command: ["/bin/sh","-c"]
              args:
                - |
                  set -eu pipefail
                  curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID

            - name: configure-s3-access-block
              image: public.ecr.aws/aws-cli/aws-cli:latest
              command: ["/bin/sh","-c"]
              args:
                - |
                  set -eu

                  aws s3api put-public-access-block \
                    --bucket "${BUCKET}" \
                    --endpoint-url "${AWS_ENDPOINT_URL}" \
                    --public-access-block-configuration file:///public-access-block-deny-all.json

                  aws s3api put-bucket-policy \
                    --bucket "${BUCKET}" \
                    --endpoint-url "${AWS_ENDPOINT_URL}" \
                    --policy file:///deny-all-policy.json
              envFrom:
                - secretRef:
                    name: all-in-one
              volumeMounts:
                - name: deny-all-policy
                  mountPath: /deny-all-policy.json
                  subPath: deny-all-policy.json
                  readOnly: true
                - name: public-access-block-deny-all
                  mountPath: /public-access-block-deny-all.json
                  subPath: public-access-block-deny-all.json
                  readOnly: true

          containers:
            - name: test
              image: alpine:3.16
              env:
                - name: VAULTWARDEN_HOST
                  value: https://vaultwarden.tryrocket.cloud
              command:
                - sh
                - -c
                - |
                  echo test

