apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: healthchecksio-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: healthchecksio
    creationPolicy: Owner
  data:
    - secretKey: HC_UUID
      remoteRef:
        key: healthchecks.io/tryrocket.cloud/vaultwarden
        property: HC_UUID
    