apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - export-and-backup-cronjob.yaml
  - all-in-one-external-secret.yaml
  - restic-external-secret.yaml
  - healthckecksio-external-secret.yaml
  # - backup-support-pvc.yaml

  - export-and-backup-cronjob-3.yaml

configMapGenerator:
  - name: helper-scripts
    files:
      - restic-backup.sh
      - hc.sh
      