apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - export-and-backup-cronjob.yaml
  - all-in-one-external-secret.yaml
  - restic-external-secret.yaml
  - healthckecksio-external-secret.yaml
  - s3-credentials-external-secret.yaml
  - s3-admin-credentials-external-secret.yaml
  - s3-connection-external-secret.yaml

  - export-and-backup-cronjob-3.yaml

configMapGenerator:
  - name: helper-scripts
    files:
      - hs.sh
      