apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: restic-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: restic
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: ionos.com/objectstorage/users/restic-backup-user
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: ionos.com/objectstorage/users/restic-backup-user
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
        property: RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
        property: RESTIC_PASSWORD
