# resticprofile.yaml
vaultwarden:
  repository: "{{ .Env.RESTIC_REPOSITORY }}/{{ .Env.BUCKET }}"
  password: "{{ .Env.RESTIC_PASSWORD }}"

  backup:
    source:
      - /export
    options:
      host: "{{ .Env.HOSTNAME }}"
      tag:
        - restic_version:"{{ .Env.RESTIC_VERSION }}"
        - bw_cli_version:"{{ .Env.BW_CLI_VERSION }}"
        - vaultwarden_version:"{{ .Env.VW_VERSION }}"
        - age_version:"{{ .Env.AGE_VERSION }}"
        - environment:production
  check:
    options:
      read-data: true
  forget:
    options:
      keep-within: "180d"
      prune: true
  env:
    - AWS_ACCESS_KEY_ID: "{{ .Env.AWS_ACCESS_KEY_ID }}"
    - AWS_SECRET_ACCESS_KEY: "{{ .Env.AWS_SECRET_ACCESS_KEY }}"
    - AWS_DEFAULT_REGION: "{{ .Env.AWS_DEFAULT_REGION }}"
