apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-admin-credentials-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: s3-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: ionos.com/objectstorage/users/0e96e074-79a3-40bd-a828-0d044a7155a4
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: ionos.com/objectstorage/users/0e96e074-79a3-40bd-a828-0d044a7155a4
        property: AWS_SECRET_ACCESS_KEY
