apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-connection-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: s3-connection
    creationPolicy: Owner
  data:
    - secretKey: BUCKET
      remoteRef:
        key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
        property: name
    - secretKey: AWS_ENDPOINT_URL
      remoteRef:
        key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
        property: endpoint
    - secretKey: AWS_REGION
      remoteRef:
        key: ionos.com/objectstorage/buckets/95225494-4d3a-423b-bc96-8ed9cfb98683
        property: region
