apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml
  - pvc.yaml
  - pv.yaml

namespace: gitea

# https://github.com/go-gitea/gitea/releases
images:
  - name: gitea/gitea:latest
    newTag: 1.22.3@sha256:76f516a1a8c27e8f8e9773639bf337c0176547a2d42a80843e3f2536787341c6
