apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.28.1
      chart: vault
      helm:
        valueFiles:
          - $values/k8s/vault/values.yaml

    - repoURL: https://github.com/tryrocket-cloud/home-ops.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/tryrocket-cloud/home-ops.git
      path: k8s/vault
      targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  info:
    - name: 'Example:'
      value: 'https://example.com'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
