apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: papra

resources:
  - ../../base
  - pvc.yaml

# https://github.com/thomiceli/opengist/releases
images:
  - name: ghcr.io/papra-hq/papra
    newTag: latest@sha256:bf4a66e776d0a40d71543747a2e17af800204b4a81d19f7951b8552c8032dbeb
