apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: papra

resources:
  - ../../base
  - pvc.yaml

# https://github.com/thomiceli/opengist/releases
images:
  - name: ghcr.io/papra-hq/papra
    newTag: latest@sha256:8e6f4d4f27f84773449dde09b50420fbfce8c916ade0fd06046c9efc7ea7b34d
