apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: papra

resources:
  - ../../base
  - pvc.yaml

# https://github.com/thomiceli/opengist/releases
images:
  - name: ghcr.io/papra-hq/papra
    newTag: latest@sha256:a1172d18d4d6f1dcdffd626a789cdf683734de0a0c87ae9fdf2bcbaabf891f9a
