apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: papra

resources:
  - ../../base
  - pvc.yaml

# https://github.com/thomiceli/opengist/releases
images:
  - name: ghcr.io/papra-hq/papra
    newTag: latest@sha256:6fdc2208f403882f4a3b8103a8aa7c2832e285f01205d54c24a9458c66607ba0
