apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  sources:
    - repoURL: https://dl.gitea.com/charts/
      targetRevision: v11.0.1
      chart: gitea
      helm:
        valueFiles:
          - $values/k8s/gitea/values.yaml

    - repoURL: https://github.com/tryrocket-cloud/home-ops.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/tryrocket-cloud/home-ops.git
      path: k8s/gitea
      targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: gitea

  info:
    - name: 'Example:'
      value: 'https://example.com'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
