# https://gitea.com/gitea/helm-chart/src/branch/main/values.yaml

strategy:
  type: 'Recreate'

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-production'
    traefik.ingress.kubernetes.io/router.middlewares: 'kube-system-https-redirect@kubernetescrd'
  hosts:
    - host: gitea.tryrocket.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gitea-tryrocket-cloud-production-tls
      hosts:
        - gitea.tryrocket.cloud

deployment:
  env:
    - name: TZ
      value: Europe/Berlin

persistence:
  claimName: gitea-pvc
  size: 4Gi
  storageClass: longhorn-retain

gitea:
  config:
    APP_NAME: 'Rocket Cloud'
    database:
      DB_TYPE: sqlite3

redis-cluster:
  enabled: false
redis:
  enabled: false
postgresql-ha:
  enabled: false
postgresql:
  enabled: false