# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: traefik
#   namespace: monitoring
#   labels:
#     release: prometheus-stack
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: traefik-dashboard
#   namespaceSelector:
#     matchNames:
#       - kube-system
#   endpoints:
#     - port: metrics
#       interval: 30s

# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: traefik
#   namespace: monitoring
#   labels:
#     release: prometheus-stack
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/instance: traefik-kube-system
#       app.kubernetes.io/name: traefik-dashboard
#   namespaceSelector:
#     matchNames:
#       - kube-system
#   endpoints:
#     - port: metrics
#       path: /metrics
#       interval: 30s


apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik
  namespace: monitoring
  labels:
    release: prometheus-stack-kube-prom-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-kube-system
      app.kubernetes.io/name: traefik
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: metrics
      interval: 30s
