apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
        - name: linkding
          image: sissbruecker/linkding:latest@sha256:0c0a9a04c7ebd644293c37f98710872fe7cdff0ea1ff7fd9be4d235e4c4678d2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: TZ
              value: Europe/Berlin
          volumeMounts:
            - name: linkding-volume
              mountPath: /etc/linkding/data
      volumes:
        - name: linkding-volume
          persistentVolumeClaim:
            claimName: linkding-pvc
