help:
	@just --list

version:
	@just --version
	@restic version
	@kopia --version
	@bw --version
	@ansible --version
	@medusa version

backup-vaultwarden:
	ansible-playbook /ansible/vaultwarden/backup-vaultwarden-export.yaml

backup-vault:
	ansible-playbook /ansible/backup-vault-export-restic.yaml