help:
	@just --list

version:
	@just --version
	@restic version
	@kopia --version
	@bw --version
	@ansible --version
	@medusa version

# ANSIBLE_STDOUT_CALLBACK=debug -vvv

backup-vaultwarden:
	ansible-playbook /ansible/vaultwarden/backup-vaultwarden-export.yaml

backup-vault:
	ansible-playbook /ansible/vault/backup-vault-export.yaml