help:
	@just --list

version:
	@just --version
	@restic version
	@bw --version
	@ansible --version
	@medusa version

# Backup application
backup tool app type:
    ansible-playbook /ansible/backup-{{tool}}-{{app}}-{{type}}.yaml

backup-vaultwarden:
	ansible-playbook /ansible/backup-restic-vaultwarden-export.yaml

backup-vault:
	ansible-playbook /ansible/backup-restic-vault-export.yaml